##Euler Problem 2
##Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  
##  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

##By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

## THE FIBONACCI GENERATOR THAT IS NOT MY CODE ## 
funcfibo <- function(n) {
  if (n < 2) 
    n
  else {
    generator <- function(f, ...) {
      c(f[2], sum(f))
    }
    Reduce(generator, 2:n, c(0,1))[2]
  }
}
### Everything below here is mine. I also have a recursive fib
### generator that I wrote, but it's way slow. 

n <- 1:100
list <- data.frame(sapply(n, funcfibo))

evens <- list[list < 4000000]
evens <- evens[evens %% 2 == 0]

sum(evens)